name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@1.0.1
        id: ssm
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          instance-ids: ${{ secrets.INSTANCE_ID }}
          working-directory: ${{ secrets.REMOTE_TARGET }}
          command: ls -al
          comment: Hello world!

      - uses: ./action-a
        with:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
